-- Source-faithful, idempotent Human Active Pharmaceutical Ingredients import.
-- Product matching deliberately normalizes only case, whitespace, and punctuation.
WITH source AS (
  SELECT btrim(value) AS name, ordinal::integer
  FROM regexp_split_to_table($human_api$
ACEBROPHYLLINE
ACECLOFENAC
ACRIFLAVINE HCL
ACYCLOVIR
ADAPALENE
ALBUTEROL SULFATE
ALENDRONATE SODIUM
ALLOPURINOL
ALPHA LIPOIC ACID
AMBROXOL HCL
AMILORIDE HCL
AMINOPHYLLINE
AMIODARONE HCL
AMISULPRIDE
AMITRIPTYLINE HCL
AMLODIPINE BESYLATE
AMODIAQUINE HCL
AMOXYCILLIN
AMPICILLIN
ARIPIPRAZOLE
ARTEMETHER
ARTESUNATE
ARTICAINE HCL
ASPIRIN
ATAZANAVIR SULFATE
ATORVASTATIN CALCIUM
AVANAFIL
AZATHIOPRINE
AZILSARTAN MEDOXOMIL
AZITHROMYCIN
BACLOFEN
BECLOMETHASONE
BENAZEPRIL HCL
BENFOTIAMINE
BENZETHONIUM CHLORIDE
BENZHEXOL
BENZOCAINE
BENZOIC ACID
BENZYL BENZOATE
BETAHISTINE HCL
BETAMETHASONE
BIPERIDEN HCL
BISACODYL
BISOPROLOL FUMARATE
BRIMONIDINE TARTRATE
BRIVARACETAM
BROMHEXINE HCL
BROMPHENIRAMINE MALEATE
BUCLIZINE HCL
BUDESONIDE
BUPARVAQUONE
BUPIVACAINE HCL
BUPROPION HCL
BUTAPHOSPHAN
CAFFEINE ANHYDROUS
CALCIPOTRIOL MONOHYDRATE
CALCIUM ASPARTATE
CALCIUM BISGLYCINATE
CALCIUM CITRATE
CALCIUM DOBESILATE
CALCIUM IODATE
CALCIUM STEARATE
CALCIUM D SACCHARATE
CANDESARTAN CILEXETIL
CARBAMAZEPINE
CARBOPOL
CARIPRAZINE HCL
CARISOPRODOL
CARPROFEN
CARVEDILOL
CEFIXIME
CEFUROXIME AXETIL
CELECOXIB
CETIRIZINE DI HCL
CETRIMIDE
CETYLPYRIDINIUM CHLORIDE
CHLORAMPHENICOL
CHLORHEXIDINE
CHLOROBUTANOL
CHLOROQUINE PHOSPHATE
CHLORPHENESIN
CHLORPHENIRAMINE MALEATE
CHLORTHALIDONE
CHLORZOXAZONE
CHROMIUM PICOLINATE
CILNIDIPINE
CINCHOCAINE HCL
CINNARIZINE
CIPROFLOXACIN
CITRIC ACID
CITALOPRAM HBR
CITICOLINE SODIUM
CLARITHROMYCIN
CLENBUTEROL HCL
CLIDINIUM BROMIDE
CLIOQUINOL
CLOBETASOL
CLOMIPRAMINE HCL
CLOPIDOGREL BISULPHATE
COENZYME Q10
COLCHICINE
CROMOGLICATE SODIUM
CROSPOVIDONE
CROTAMITON
CYPROHEPTADINE HCL
DABIGATRAN
DANAZOL
DAPOXETIN HCL
DEFLAZACORT
DESLORATADINE
DESOXIMETASONE USP
DESVENLAFAXINE
DEXAMETHASONE
DEXCHLORPHENIRAMINE MALEATE
DEXKETOPROFEN TROMETAMOL
DEXLANSOPRAZOLE
DEXTROMETHORPHAN HBR
DIACEREIN
DIBUCAINE HCL
DICLOFENAC
DICYCLOMINE HCL
DIETHYLCARBAMAZINE CITRATE
DIGOXIN
DI-IODOHYDROXYQUINOLINE
DILOXANIDE FUROATE
DILTIAZEM HCL
DIMENHYDRINATE
DIMINAZENE DIACETURATE
DIPHENHYDRAMINE HCL
DISULFIRAM
DIVALPROEX SODIUM
DOBUTAMINE HCL
DOCUSATE SODIUM
DOLUTEGRAVIR SODIUM
DOMPERIDONE
DONEPEZIL HCL
DORZOLAMIDE HCL
DOXAZOSIN MESYLATE
DOXYLAMINE SUCCINATE
DULOXETINE HCL
ECONAZOLE NITRATE
ERYTHROMYCIN
ESCITALOPRAM OXALATE
ESOMEPRAZOLE
ETAMSYLATE
ETHAMBUTOL HCL
ETHYL OLEATE
ETODOLAC
ETORICOXIB
EZETIMIBE
FAMOTIDINE
FAVIPIRAVIR
FEBUXOSTAT
FENOFIBRATE
FENTICONAZOLE NITRATE
FERROUS ASCORBATE
FERROUS BIGLYCINATE
FERROUS FUMARATE
FERROUS GLUCONATE
FERROUS SULFATE
FEXOFENADINE HCL
FLAVOXATE HCL
FLUCINOLONE ACETONIDE
FLUCLOXACILLIN SODIUM
FLUCONAZOLE
FLUNARIZINE
FLUNIXIN MEGLUMINE
FLUOXETINE HCL
FLUPHENAZINE
FLUTICASONE
FOLIC ACID
FORMOTEROL FUMARATE
FUROSEMIDE
GABAPENTIN
GEMCITABINE HCL
GLIBENCLAMIDE
GLICLAZIDE
GLIMEPIRIDE
GLIPIZIDE
GLUCOSAMINE SULFATE
GLYCEROPHOSPHATES (NA, CA, MG)
GLYCOPYRROLATE
GRANISETRON HCL
GUAIFENESIN
HALOBETASOL PROPIONATE
HALOPERIDOL
HOMATROPINE METHYL BROMIDE
HOMIDIUM CHLORIDE
HYDRALAZINE HCL
HYDROCHLOROTHIAZIDE
HYDROCORTISONE
HYDROXOCOBALAMINE SULPHATE
HYDROXYZINE HCL
HYOSCINE BUTYL BROMIDE
IBANDRONATE SODIUM
IBANDRONIC ACID
IBRUTINIB
IBUPROFEN
IGURATIMOD
IMATINIB
IMIDOCARB DIPROPIONATE
IMIPRAMINE HCL
IODOFORM
IPRATROPIUM BROMIDE
IRBESARTAN
IRON SUCROSE
IRON (III) HYDROXY POLYMALTOSE
IRON DEXTRAN POWDER
ISOMETAMIDIUM
ISONIAZIDE
ISOSORBIDE
ITOPRIDE HCL
ITRACONAZOLE
IVABRADINE HCL
IVERMECTIN
KETOCONAZOLE
KETOPROFEN
KETOROLAC TROMETHAMINE
LABETALOL
LACTOSE
LAMOTRIGINE
LANSOPRAZOLE POWDER
LEFLUNOMIDE
LENALIDOMIDE
LERCANIDIPINE
LEVETIRACETAM
LEVOCETIRIZINE HCL
LEVOFLOXACIN
LEVOSALBUTAMOL SULPHATE
LEVOSULPIRIDE
LIDCAINE HCL/BASE
LINEZOLID
LISINOPRIL
LOPERAMIDE
LORATADINE
LORNOXICAM
LOSARTAN POTASSIUM
LOTEPREDNOL ETABONATE
LOVASTATIN
L-SELEMETHIONINE
LULICONAZOLE
LUMEFANTRINE
MARBOFLOXACIN
MEBENDAZOLE
MEBEVERINE HCL
MECLIZINE HCL
MEFENAMIC ACID
MEGLUMINE
MELATONIN
MELOXICAM
MEMANTINE HCL
MEPHENESIN
MEPIVACAINE
MEPYRAMINE MALEATE
MERCUROCHROME
MESALAMINE (MESALAZINE)
METFORMIN HCL
METHOCARBAMOL
METHSCOPOLAMINE BROMIDE
METHYLENE BLUE
METHYLPREDNISOLONE
METOCLOPRAMIDE HCL
METOPROLOL
METRONIDAZOLE BENZOATE
MICONAZOLE NITRATE
MINOXIDIL
MIRTAZAPINE
MODAFINIL
MOLNUPIRAVIR
MOMETASONE FUROATE
MONTELUKAST SODIUM
MOXIFLOXACIN HCL
MUPIROCIN
MYCOPHENOLATE
NAFTIDROFURYL
NALBUPHINE HCL
NALIDIXIC ACID
NALTREXONE HCL
NANDROLONE
NAPHAZOLINE
NEBIVOLOL HCL
NIACINAMIDE
NICLOSAMIDE
NICORANDIL
NICOTINAMIDE
NICOTINIC ACID
NIFEDIPINE
NIMESULIDE
NITAZOXANIDE
NITROFURATOIN
NORTRIPTYLLINE HCL
OFLOXACIN
OLANZAPINE
OLMESARTAN MEDOXOMIL
OLOPATADINE
OMEPRAZOLE
ONDANSETRON
ORNIDAZOLE
ORPHENADRINE CITRATE
OSELTAMIVIR PHOSPHATE
OXCABAMAZEPINE
OXOMEMAZINE
OXYBUTYNIN
OXYMETAZOLINE HCL
OXYTETRACYCLINE
P.V.P (POVIDON K30)
PAMABROM
PANTOPRAZOLE
PARA AMINO BENZOIC ACID
PARACETAMOL
PAROXETINE
PHENAZOPYRIDINE HCL
PHENIRAMINE MALEATE
PHENOBARBITAL
PHENYLEPHRINE HCL
PHENYTOIN
PICOLINIC ACID
PICOSULFATE SODIUM
PIDOTIMOD
PIOGLITAZONE
PIPERAQUINE PHOSPHATE
PIRFENIDONE
PIROXICAM
POVIDONE IODINE
PRAZIQUANTEL
PREDNISOLONE
PREGABALIN
PRIMAQUINE PHOSPHATE
PROCAINE HCL
PROCHLORPERAZINE
PROCYCLIDINE HCL
PROMETHAZINE HCL
PROPRANOLOL HCL
PROPYPHENAZONE
PYRILAMINE MALEATE
PYRIMETHAMINE
QUETIAPINE FUMARATE
QUININE SULPHATE
RABEPRAZOLE SODIUM
RACECADOTRIL
RACTOPAMINE HCL
RANITIDINE HCL
RANOLAZINE
RESPERIDONE
RIBOFLAVIN PHOSPHATE
RIFAXIMIN
RISEDRONATE SODIUM
RISPERIDONE
RIVAROXABAN
RIVASTIGMINE
ROSUVASTATINE CALCIUM
ROXARSONE
ROXITHROMYCIN
RUPATADINE FUMARATE
SACCHARIN SODIUM
SALBUTAMOL SULPHATE
SALMETEROL XINAFOATE
SECNIDAZOLE
SELEGILINE HCL
SELENIUM SULPHIDE
SERTACONAZOLE NITRATE
SETRALINE HCL
SEVELAMER HCL
SILDENAFIL CITRATE
SILODOSIN
SILVER SULFADIAZINE
SIMETHICONE EMULSION
SIMVASTAIN
SITAGLIPTIN PHOSPHATE
SODIUM STEARYL FUMARATE
SODIUM VALPROATE
SOLIFENACIN SUCCINATE
SORAFENIB TOSYLATE
SUCCINYL CHOLINE CHLORIDE
SUCRALFATE
SULFADOXINE
SULFAMETHIZOLE
SULFAMETHOXAZOLE
SULFAPYRIDINE
SULFASALAZINE
SUMATRIPTAN SUCCINATE
SUNITINIB MALATE
TACROLIMUS
TADALAFIL
TAMOXIFEN CITRATE
TAMSULOSIN HCL
TAPENTADOL HCL
TAZAROTENE
TELMISARTAN
TEMOZOLOMIDE
TENOFOVIR
TERBUTALINE SULPHATE
TETRACAINE HCL
THEOPHYLINE
TICAGRELOR
TIMOLOL MALEATE
TINIDAZOLE
TIZANIDINE HCL
TOLFENAMIC ACID
TOLNAFTATE
TOLTRAZURIL
TOPIRAMATE
TORSEMIDE
TRANEXAMIC ACID
TRAZODONE HCL
TRIAMCINOLONE ACETONIDE
TRIFLUOPERAZINE HCL
TRIHEXYPHENIDYL HCL
TRIMETAZIDINE DIHCL
TRIMETHOPRIM
TRIPROLIDINE HCL
TROPICAMIDE
URSODEOXYCHOLIC ACID
VALGANCYCLOVIR
VALPROIC ACID
VALSARTAN
VARDENAFIL
VENLAFAXINE HCL
VERAPAMIL HCL
VILDAGLIPTIN
VITAMIN B1 (THIAMINE HCL)
VITAMIN E OILY
VOGLIBOSE
WARFARIN SODIUM
XYLOMETAZOLINE HCL
$human_api$, E'\\r?\\n') WITH ORDINALITY AS rows(value, ordinal)
  WHERE btrim(value) <> ''
),
category AS (
  SELECT id, name FROM categories
  WHERE slug = 'human-active-pharmaceutical-ingredients'
),
matched AS (
  SELECT source.name, source.ordinal, product.id
  FROM source
  JOIN LATERAL (
    SELECT p.id
    FROM products p
    WHERE regexp_replace(lower(btrim(p.name)), '[^a-z0-9]+', '', 'g')
          = regexp_replace(lower(source.name), '[^a-z0-9]+', '', 'g')
       OR p.slug = trim(both '-' from regexp_replace(lower(source.name), '[^a-z0-9]+', '-', 'g'))
    ORDER BY
      CASE WHEN lower(btrim(p.name)) = lower(source.name) THEN 0 ELSE 1 END,
      p.created_at
    LIMIT 1
  ) product ON true
),
inserted AS (
  INSERT INTO products (
    name, slug, category, grade, cas_number, overview, applications,
    documentation, featured, active, sort_order
  )
  SELECT
    source.name,
    trim(both '-' from regexp_replace(lower(source.name), '[^a-z0-9]+', '-', 'g')),
    category.name,
    '{}'::text[],
    NULL,
    '',
    '{}'::text[],
    '{}'::text[],
    false,
    true,
    current_max.value + source.ordinal
  FROM source
  CROSS JOIN category
  CROSS JOIN (SELECT COALESCE(max(sort_order), 0) AS value FROM products) current_max
  LEFT JOIN matched ON matched.name = source.name
  WHERE matched.id IS NULL
  ON CONFLICT (slug) DO NOTHING
  RETURNING id
)
SELECT count(*) AS new_products_inserted FROM inserted;

WITH source AS (
  SELECT btrim(value) AS name
  FROM regexp_split_to_table($human_api$
ACEBROPHYLLINE
ACECLOFENAC
ACRIFLAVINE HCL
ACYCLOVIR
ADAPALENE
ALBUTEROL SULFATE
ALENDRONATE SODIUM
ALLOPURINOL
ALPHA LIPOIC ACID
AMBROXOL HCL
AMILORIDE HCL
AMINOPHYLLINE
AMIODARONE HCL
AMISULPRIDE
AMITRIPTYLINE HCL
AMLODIPINE BESYLATE
AMODIAQUINE HCL
AMOXYCILLIN
AMPICILLIN
ARIPIPRAZOLE
ARTEMETHER
ARTESUNATE
ARTICAINE HCL
ASPIRIN
ATAZANAVIR SULFATE
ATORVASTATIN CALCIUM
AVANAFIL
AZATHIOPRINE
AZILSARTAN MEDOXOMIL
AZITHROMYCIN
BACLOFEN
BECLOMETHASONE
BENAZEPRIL HCL
BENFOTIAMINE
BENZETHONIUM CHLORIDE
BENZHEXOL
BENZOCAINE
BENZOIC ACID
BENZYL BENZOATE
BETAHISTINE HCL
BETAMETHASONE
BIPERIDEN HCL
BISACODYL
BISOPROLOL FUMARATE
BRIMONIDINE TARTRATE
BRIVARACETAM
BROMHEXINE HCL
BROMPHENIRAMINE MALEATE
BUCLIZINE HCL
BUDESONIDE
BUPARVAQUONE
BUPIVACAINE HCL
BUPROPION HCL
BUTAPHOSPHAN
CAFFEINE ANHYDROUS
CALCIPOTRIOL MONOHYDRATE
CALCIUM ASPARTATE
CALCIUM BISGLYCINATE
CALCIUM CITRATE
CALCIUM DOBESILATE
CALCIUM IODATE
CALCIUM STEARATE
CALCIUM D SACCHARATE
CANDESARTAN CILEXETIL
CARBAMAZEPINE
CARBOPOL
CARIPRAZINE HCL
CARISOPRODOL
CARPROFEN
CARVEDILOL
CEFIXIME
CEFUROXIME AXETIL
CELECOXIB
CETIRIZINE DI HCL
CETRIMIDE
CETYLPYRIDINIUM CHLORIDE
CHLORAMPHENICOL
CHLORHEXIDINE
CHLOROBUTANOL
CHLOROQUINE PHOSPHATE
CHLORPHENESIN
CHLORPHENIRAMINE MALEATE
CHLORTHALIDONE
CHLORZOXAZONE
CHROMIUM PICOLINATE
CILNIDIPINE
CINCHOCAINE HCL
CINNARIZINE
CIPROFLOXACIN
CITRIC ACID
CITALOPRAM HBR
CITICOLINE SODIUM
CLARITHROMYCIN
CLENBUTEROL HCL
CLIDINIUM BROMIDE
CLIOQUINOL
CLOBETASOL
CLOMIPRAMINE HCL
CLOPIDOGREL BISULPHATE
COENZYME Q10
COLCHICINE
CROMOGLICATE SODIUM
CROSPOVIDONE
CROTAMITON
CYPROHEPTADINE HCL
DABIGATRAN
DANAZOL
DAPOXETIN HCL
DEFLAZACORT
DESLORATADINE
DESOXIMETASONE USP
DESVENLAFAXINE
DEXAMETHASONE
DEXCHLORPHENIRAMINE MALEATE
DEXKETOPROFEN TROMETAMOL
DEXLANSOPRAZOLE
DEXTROMETHORPHAN HBR
DIACEREIN
DIBUCAINE HCL
DICLOFENAC
DICYCLOMINE HCL
DIETHYLCARBAMAZINE CITRATE
DIGOXIN
DI-IODOHYDROXYQUINOLINE
DILOXANIDE FUROATE
DILTIAZEM HCL
DIMENHYDRINATE
DIMINAZENE DIACETURATE
DIPHENHYDRAMINE HCL
DISULFIRAM
DIVALPROEX SODIUM
DOBUTAMINE HCL
DOCUSATE SODIUM
DOLUTEGRAVIR SODIUM
DOMPERIDONE
DONEPEZIL HCL
DORZOLAMIDE HCL
DOXAZOSIN MESYLATE
DOXYLAMINE SUCCINATE
DULOXETINE HCL
ECONAZOLE NITRATE
ERYTHROMYCIN
ESCITALOPRAM OXALATE
ESOMEPRAZOLE
ETAMSYLATE
ETHAMBUTOL HCL
ETHYL OLEATE
ETODOLAC
ETORICOXIB
EZETIMIBE
FAMOTIDINE
FAVIPIRAVIR
FEBUXOSTAT
FENOFIBRATE
FENTICONAZOLE NITRATE
FERROUS ASCORBATE
FERROUS BIGLYCINATE
FERROUS FUMARATE
FERROUS GLUCONATE
FERROUS SULFATE
FEXOFENADINE HCL
FLAVOXATE HCL
FLUCINOLONE ACETONIDE
FLUCLOXACILLIN SODIUM
FLUCONAZOLE
FLUNARIZINE
FLUNIXIN MEGLUMINE
FLUOXETINE HCL
FLUPHENAZINE
FLUTICASONE
FOLIC ACID
FORMOTEROL FUMARATE
FUROSEMIDE
GABAPENTIN
GEMCITABINE HCL
GLIBENCLAMIDE
GLICLAZIDE
GLIMEPIRIDE
GLIPIZIDE
GLUCOSAMINE SULFATE
GLYCEROPHOSPHATES (NA, CA, MG)
GLYCOPYRROLATE
GRANISETRON HCL
GUAIFENESIN
HALOBETASOL PROPIONATE
HALOPERIDOL
HOMATROPINE METHYL BROMIDE
HOMIDIUM CHLORIDE
HYDRALAZINE HCL
HYDROCHLOROTHIAZIDE
HYDROCORTISONE
HYDROXOCOBALAMINE SULPHATE
HYDROXYZINE HCL
HYOSCINE BUTYL BROMIDE
IBANDRONATE SODIUM
IBANDRONIC ACID
IBRUTINIB
IBUPROFEN
IGURATIMOD
IMATINIB
IMIDOCARB DIPROPIONATE
IMIPRAMINE HCL
IODOFORM
IPRATROPIUM BROMIDE
IRBESARTAN
IRON SUCROSE
IRON (III) HYDROXY POLYMALTOSE
IRON DEXTRAN POWDER
ISOMETAMIDIUM
ISONIAZIDE
ISOSORBIDE
ITOPRIDE HCL
ITRACONAZOLE
IVABRADINE HCL
IVERMECTIN
KETOCONAZOLE
KETOPROFEN
KETOROLAC TROMETHAMINE
LABETALOL
LACTOSE
LAMOTRIGINE
LANSOPRAZOLE POWDER
LEFLUNOMIDE
LENALIDOMIDE
LERCANIDIPINE
LEVETIRACETAM
LEVOCETIRIZINE HCL
LEVOFLOXACIN
LEVOSALBUTAMOL SULPHATE
LEVOSULPIRIDE
LIDCAINE HCL/BASE
LINEZOLID
LISINOPRIL
LOPERAMIDE
LORATADINE
LORNOXICAM
LOSARTAN POTASSIUM
LOTEPREDNOL ETABONATE
LOVASTATIN
L-SELEMETHIONINE
LULICONAZOLE
LUMEFANTRINE
MARBOFLOXACIN
MEBENDAZOLE
MEBEVERINE HCL
MECLIZINE HCL
MEFENAMIC ACID
MEGLUMINE
MELATONIN
MELOXICAM
MEMANTINE HCL
MEPHENESIN
MEPIVACAINE
MEPYRAMINE MALEATE
MERCUROCHROME
MESALAMINE (MESALAZINE)
METFORMIN HCL
METHOCARBAMOL
METHSCOPOLAMINE BROMIDE
METHYLENE BLUE
METHYLPREDNISOLONE
METOCLOPRAMIDE HCL
METOPROLOL
METRONIDAZOLE BENZOATE
MICONAZOLE NITRATE
MINOXIDIL
MIRTAZAPINE
MODAFINIL
MOLNUPIRAVIR
MOMETASONE FUROATE
MONTELUKAST SODIUM
MOXIFLOXACIN HCL
MUPIROCIN
MYCOPHENOLATE
NAFTIDROFURYL
NALBUPHINE HCL
NALIDIXIC ACID
NALTREXONE HCL
NANDROLONE
NAPHAZOLINE
NEBIVOLOL HCL
NIACINAMIDE
NICLOSAMIDE
NICORANDIL
NICOTINAMIDE
NICOTINIC ACID
NIFEDIPINE
NIMESULIDE
NITAZOXANIDE
NITROFURATOIN
NORTRIPTYLLINE HCL
OFLOXACIN
OLANZAPINE
OLMESARTAN MEDOXOMIL
OLOPATADINE
OMEPRAZOLE
ONDANSETRON
ORNIDAZOLE
ORPHENADRINE CITRATE
OSELTAMIVIR PHOSPHATE
OXCABAMAZEPINE
OXOMEMAZINE
OXYBUTYNIN
OXYMETAZOLINE HCL
OXYTETRACYCLINE
P.V.P (POVIDON K30)
PAMABROM
PANTOPRAZOLE
PARA AMINO BENZOIC ACID
PARACETAMOL
PAROXETINE
PHENAZOPYRIDINE HCL
PHENIRAMINE MALEATE
PHENOBARBITAL
PHENYLEPHRINE HCL
PHENYTOIN
PICOLINIC ACID
PICOSULFATE SODIUM
PIDOTIMOD
PIOGLITAZONE
PIPERAQUINE PHOSPHATE
PIRFENIDONE
PIROXICAM
POVIDONE IODINE
PRAZIQUANTEL
PREDNISOLONE
PREGABALIN
PRIMAQUINE PHOSPHATE
PROCAINE HCL
PROCHLORPERAZINE
PROCYCLIDINE HCL
PROMETHAZINE HCL
PROPRANOLOL HCL
PROPYPHENAZONE
PYRILAMINE MALEATE
PYRIMETHAMINE
QUETIAPINE FUMARATE
QUININE SULPHATE
RABEPRAZOLE SODIUM
RACECADOTRIL
RACTOPAMINE HCL
RANITIDINE HCL
RANOLAZINE
RESPERIDONE
RIBOFLAVIN PHOSPHATE
RIFAXIMIN
RISEDRONATE SODIUM
RISPERIDONE
RIVAROXABAN
RIVASTIGMINE
ROSUVASTATINE CALCIUM
ROXARSONE
ROXITHROMYCIN
RUPATADINE FUMARATE
SACCHARIN SODIUM
SALBUTAMOL SULPHATE
SALMETEROL XINAFOATE
SECNIDAZOLE
SELEGILINE HCL
SELENIUM SULPHIDE
SERTACONAZOLE NITRATE
SETRALINE HCL
SEVELAMER HCL
SILDENAFIL CITRATE
SILODOSIN
SILVER SULFADIAZINE
SIMETHICONE EMULSION
SIMVASTAIN
SITAGLIPTIN PHOSPHATE
SODIUM STEARYL FUMARATE
SODIUM VALPROATE
SOLIFENACIN SUCCINATE
SORAFENIB TOSYLATE
SUCCINYL CHOLINE CHLORIDE
SUCRALFATE
SULFADOXINE
SULFAMETHIZOLE
SULFAMETHOXAZOLE
SULFAPYRIDINE
SULFASALAZINE
SUMATRIPTAN SUCCINATE
SUNITINIB MALATE
TACROLIMUS
TADALAFIL
TAMOXIFEN CITRATE
TAMSULOSIN HCL
TAPENTADOL HCL
TAZAROTENE
TELMISARTAN
TEMOZOLOMIDE
TENOFOVIR
TERBUTALINE SULPHATE
TETRACAINE HCL
THEOPHYLINE
TICAGRELOR
TIMOLOL MALEATE
TINIDAZOLE
TIZANIDINE HCL
TOLFENAMIC ACID
TOLNAFTATE
TOLTRAZURIL
TOPIRAMATE
TORSEMIDE
TRANEXAMIC ACID
TRAZODONE HCL
TRIAMCINOLONE ACETONIDE
TRIFLUOPERAZINE HCL
TRIHEXYPHENIDYL HCL
TRIMETAZIDINE DIHCL
TRIMETHOPRIM
TRIPROLIDINE HCL
TROPICAMIDE
URSODEOXYCHOLIC ACID
VALGANCYCLOVIR
VALPROIC ACID
VALSARTAN
VARDENAFIL
VENLAFAXINE HCL
VERAPAMIL HCL
VILDAGLIPTIN
VITAMIN B1 (THIAMINE HCL)
VITAMIN E OILY
VOGLIBOSE
WARFARIN SODIUM
XYLOMETAZOLINE HCL
$human_api$, E'\\r?\\n') AS rows(value)
  WHERE btrim(value) <> ''
),
category AS (
  SELECT id FROM categories
  WHERE slug = 'human-active-pharmaceutical-ingredients'
),
matched_products AS (
  SELECT source.name, product.id
  FROM source
  JOIN LATERAL (
    SELECT p.id
    FROM products p
    WHERE regexp_replace(lower(btrim(p.name)), '[^a-z0-9]+', '', 'g')
          = regexp_replace(lower(source.name), '[^a-z0-9]+', '', 'g')
       OR p.slug = trim(both '-' from regexp_replace(lower(source.name), '[^a-z0-9]+', '-', 'g'))
    ORDER BY
      CASE WHEN lower(btrim(p.name)) = lower(source.name) THEN 0 ELSE 1 END,
      p.created_at
    LIMIT 1
  ) product ON true
),
inserted AS (
  INSERT INTO product_categories (product_id, category_id)
  SELECT matched_products.id, category.id
  FROM matched_products
  CROSS JOIN category
  ON CONFLICT DO NOTHING
  RETURNING product_id
)
SELECT count(*) AS new_relationships_inserted FROM inserted;
